name: Release

on:
  push:
    branches: ["main"]

concurrency:
  group: packages
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx --yes \
              --package semantic-release@25 \
              --package @semantic-release/exec@7 \
              --package conventional-changelog-conventionalcommits \
              semantic-release
